api/urls.py
from django.conf import settings
from django.urls import include, path
from drf_yasg.utils import swagger_auto_schema
from rest_framework import routers, permissions
import api.views

from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="LevEchad API",
        default_version='v1',
        # description="",
        # terms_of_service="https://www.google.com/policies/terms/",
        # contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

router = routers.DefaultRouter()
router.register(r'registration', api.views.RegistrationViewSet, basename='registration')
router.register(r'updatevolunteer', api.views.UpdateVolunteerViewSet, basename='update_volunteer')
router.register(r'SetVolunteerFreeze', api.views.VolunteerFreezeViewSet, basename='SetVolunteerFreeze')
router.register(r'DisableVolunteerFreeze', api.views.DisableFreezesViewSet, basename='DisableVolunteerFreeze')
router.register(r'createhelprequest', api.views.CreateHelpRequestViewSet, basename='create_help_request')
router.register(r'volunteers', api.views.VolunteersViewSet, basename='volunteer_list')
router.register(r'helprequests', api.views.HelpRequestsViewSet, basename='help_request_list')
router.register(r'maphelprequests', api.views.HelpRequestMapViewSet, basename='map_help_request_list')
router.register(r'updatehelprequest', api.views.UpdateHelpRequestViewSet, basename='update_help_request_list')
router.register(r'cityautocomplete', api.views.CityAutocompleteViewSet, basename='city_autocomplete')
router.register(r'areas', api.views.AreasViewSet, basename='area_list')
router.register(r'languages', api.views.LanguagesViewSet, basename='language_list')
router.register(r'sendverificationcode', api.views.SendVerificationCodeViewSet, basename='send_verification_code')
router.register(r'checkverificationcode', api.views.CheckVerificationCodeViewSet, basename='check_verification_code')

authTokenView = \
    swagger_auto_schema(
        method='post',
        request_body=api.views.CustomAuthToken.serializer_class
    )(api.views.CustomAuthToken.as_view())

urlpatterns = [
    path('', include(router.urls)),
    path('getGoogleApiSecret/', api.views.GetGoogleApiSecret.as_view()),
    path('authtoken/', authTokenView if settings.ENV != 'PRODUCTION' else api.views.CustomAuthToken.as_view()),
]
if settings.ENV != 'PRODUCTION':
    urlpatterns.append(path('docs/', schema_view.with_ui('swagger', cache_timeout=0)))

client/urls.py
from django.urls import path
from django.conf import settings
from . import views


urlpatterns = [
    path('', views.homepage, name='client_home'),
    path('thanks', views.thanks),
    path('thanks_volunteer', views.thanks_volunteer),

    path('volunteer', views.volunteer_view, name='client_volunteer'),
    path('find_certificate', views.find_certificate_view, name='client_find_certificate'),
    path('schedule', views.schedule),

    path('get_help', views.get_help, name='client_get_help'),
    path('help/medic', views.medic_help),
    path('help/other', views.other_help),
    path('help/phone', views.phone_help),
    path('help/shopping', views.shopping_help),
    path('help/travel', views.travel_help),
    path('help/workers', views.workers_help),
]

if settings.DEBUG:
    urlpatterns += [path('download_certificate/<int:pk>', views.download_certificate_view, name='download_certificate')]

levechad/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', lambda request: redirect('client/', permanent=False)),
    path('admin/', admin.site.urls),
    path('server/', include('server.urls')),
    path('client/', include('client.urls')),
    path('api/', include('api.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client/models.py
# coding=utf-8
import os
from datetime import date
from uuid import uuid4

import boto3
from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.files.base import ContentFile
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import F, Count, Q
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils import timezone
from multiselectfield import MultiSelectField

import client.geo
from client import certificates

DEFAULT_MAX_FIELD_LENGTH = 200
SHORT_FIELD_LENGTH = 20
ID_LENGTH = 11
DAY_NAME_LENGTH = 3


class Timestampable(models.Model):
    created_date = models.DateTimeField(null=True, editable=False)
    updated_date = models.DateTimeField(null=True, editable=False)

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        # Update timestamps on save
        if not self.id:
            self.created_date = timezone.now()
        self.updated_date = timezone.now()
        return super(Timestampable, self).save(*args, **kwargs)


class Area(models.Model):
    name = models.CharField(max_length=SHORT_FIELD_LENGTH, primary_key=True)

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=DEFAULT_MAX_FIELD_LENGTH, primary_key=True)

    def __str__(self):
        return self.name


class City(models.Model):
    name = models.CharField(max_length=DEFAULT_MAX_FIELD_LENGTH, primary_key=True)
    x = models.FloatField()
    y = models.FloatField()
    region = models.ForeignKey(Area, on_delete=models.PROTECT, null=True)

    def __str__(self):
        return self.name


class VolunteerSchedule(Timestampable):
    end_date = models.DateField(null=True, blank=True)
    Sunday = models.CharField(max_length=DAY_NAME_LENGTH, blank=True)
    Monday = models.CharField(max_length=DAY_NAME_LENGTH, blank=True)
    Tuesday = models.CharField(max_length=DAY_NAME_LENGTH, blank=True)
    Wednesday = models.CharField(max_length=DAY_NAME_LENGTH, blank=True)
    Thursday = models.CharField(max_length=DAY_NAME_LENGTH, blank=True)
    Friday = models.CharField(max_length=DAY_NAME_LENGTH, blank=True)
    Saturday = models.CharField(max_length=DAY_NAME_LENGTH, blank=True)


class ExtendedVolunteerManager(models.Manager):
    @staticmethod
    def _add_distance_old(qs, helprequest_coordinates, as_int=False):
        """
        This function is DEPRECATED and will be removed in future releases.
        Kept for compatibility with older system (and to keep new features for the upgraded one)
        :param qs:
        :param helprequest_coordinates:
        :param as_int:
        :return:
        """
        qs = qs.annotate(y_distance=(F('city__y') - helprequest_coordinates[1]) ** 2)
        qs = qs.annotate(x_distance=(F('city__x') - helprequest_coordinates[0]) ** 2)
        qs = qs.annotate(distance=models.ExpressionWrapper(((F('x_distance') + F('y_distance')) ** 0.5) / 100,
                                                           output_field=models.IntegerField() if as_int
                                                           else models.FloatField()))
        return qs

    @staticmethod
    def _add_distance(qs, helprequest_coordinates, as_int=False):
        """
        Uses pithagoras to calculate distance roughly, until an exact algorithm will be implemented.
        THE EARTH IS NOT FLAT, Israel is simply a small country :)
        :param qs:
        :param helprequest_coordinates:
        :param as_int:
        :return:
        """
        qs = qs.annotate(latitude_distance=(F('location_latitude') - helprequest_coordinates[0]) ** 2)
        qs = qs.annotate(longitude_distance=(F('location_longitude') - helprequest_coordinates[1]) ** 2)
        qs = qs.annotate(
            distance=models.ExpressionWrapper(((F('latitude_distance') + F('longitude_distance')) ** 0.5) / 100,
                                              output_field=models.IntegerField() if as_int
                                              else models.FloatField()))
        return qs

    @staticmethod
    def _add_num_helprequests(qs):
        qs = qs.annotate(num_helprequests=Count('helprequest'))
        return qs

    def get_queryset(self):
        return super().get_queryset().filter(disabled=False)

    def all_by_distance(self, helprequest_coordinates):
        volunteers_qs = self.get_queryset()
        volunteers_qs = self._add_distance_old(volunteers_qs, helprequest_coordinates)
        return volunteers_qs.order_by('distance')

    def all_by_score(self, helprequest_coordinates):
        # In the future, add more parameters
        volunteers_qs = self.get_queryset()
        # Remove volunteers on hold.
        volunteers_qs = volunteers_qs.filter(
            ~Q(freezes__expiration_date__gte=date.today(),
               freezes__freeze_disabled=False)
        )
        # Used to catch use of old coordinate system (mainly the legacy website).
        if helprequest_coordinates[0] > 1000:
            volunteers_qs = self._add_distance_old(volunteers_qs, helprequest_coordinates, as_int=True)
        else:
            volunteers_qs = self._add_distance(volunteers_qs, helprequest_coordinates, as_int=True)
        volunteers_qs = self._add_num_helprequests(volunteers_qs)
        return volunteers_qs.order_by('distance', 'num_helprequests')

    def all_with_helprequests_count(self):
        volunteers_qs = self.get_queryset()
        volunteers_qs = self._add_num_helprequests(volunteers_qs)
        return volunteers_qs


class Volunteer(Timestampable):
    objects = ExtendedVolunteerManager()
    MOVING_WAYS = (
        ("BIKE", "אופניים"),
        ("SCOOTER", "קטנוע"),
        ("CAR", "מכונית"),
        ("PUBL", "תחבורה ציבורית"),
        ("FOOT", "רגלית")
    )
    HEARING_WAYS = (
        ("FB_INST", "פייסבוק ואינסטגרם"),
        ("WHTSP", "ווצאפ"),
        ("RAD_TV", "רדיו וטלוויזיה"),
        ("OTHR", "אחר")
    )
    DEFAULT_TYPE = "MISSIONS"
    TYPES = (
        ("NIGHBORHOOD_COORDINATOR", "רכז שכונה"),
        ("CITY_COORDINATOR", "רכז עיר"),
        ("STAFF", "מטה"),
        ("HAMAL", "חמל"),
        ("PROJECT", "פרויקט"),
        ("CHILD_CARE", "משפחתון"),
        ("AGRICULTURE", "חקלאות"),
        (DEFAULT_TYPE, "משימות")
    )

    WANTED_ASSIGNMENTS = (
        ("FOOD", "חלוקת מזון"),
        ("MEDICINES", "משלוח תרופות"),
        ("STAFF", "סיוע לעובדים חיוניים"),
        ("TRANSPORTATION", "הסעות"),
        ("TELEPHONE SUPPORT", "תמיכה טלפונית"),
        ("CHILD_CARE", "עזרה במשפחתונים"),
        ("OTHER", "אחר"),
    )

    GENDERS = (
        ('MALE', 'זכר'),
        ('FEMALE', 'נקבה'),
        ('OTHER', 'מגדר אחר'),
    )

    _original_values = {
        'first_name': None,
        'last_name': None,
        'tz_number': None
    }

    def _update_original_values(self):
        """
        Updates the dict used to keep track of changes in certain fields between changes
        """
        self._original_values['tz_number'] = self.tz_number
        self._original_values['first_name'] = self.first_name
        self._original_values['last_name'] = self.last_name

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._update_original_values()

    def save(self, *args, **kwargs):
        if self.id is not None:
            for key, value in self._original_values.items():
                if getattr(self, key) != value:
                    # A change occurred in one of the fields listed in the dict - update valid certificates images
                    for certificate in self.get_active_certificates():
                        certificate.create_image()

                    break

        super().save(*args, **kwargs)
        self._update_original_values()

    def get_or_generate_valid_certificate(self):
        certificate = self.get_active_certificates().first()
        if certificate is None:
            certificate = VolunteerCertificate.objects.create(volunteer_id=self.id)

        return certificate

    def get_active_certificates(self):
        """
        Returns the active certificates a volunteer has, ordered by expiration date (first certificate has
        most time to live)
        """
        return self.certificates.filter(expiration_date__gte=date.today()).order_by('-expiration_date')

    tz_number = models.CharField(max_length=ID_LENGTH, blank=True)
    first_name = models.CharField(max_length=DEFAULT_MAX_FIELD_LENGTH, default="")
    last_name = models.CharField(max_length=DEFAULT_MAX_FIELD_LENGTH, default="")
    organization = models.CharField(max_length=DEFAULT_MAX_FIELD_LENGTH, null=True, blank=True)
    age = models.IntegerField(null=True, blank=True, default=None)
    gender = models.CharField(max_length=SHORT_FIELD_LENGTH, choices=GENDERS, null=True, default=None, blank=True)
    date_of_birth = models.DateField(null=True, blank=True, default=None)
    # What is volunteer_type? wanted_assignments is kind of the same...
    volunteer_type = models.CharField(
        max_length=DEFAULT_MAX_FIELD_LENGTH,
        choices=TYPES,
        null=True,
        blank=True,
        default=DEFAULT_TYPE
    )
    wanted_assignments = MultiSelectField(choices=WANTED_ASSIGNMENTS, default=[item[0] for item in WANTED_ASSIGNMENTS])
    week_assignments_capacity = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(10)])
    areas = models.ManyToManyField(Area, blank=True)
    languages = models.ManyToManyField(Language)
    phone_number = models.CharField(max_length=DEFAULT_MAX_FIELD_LENGTH)
    email = models.EmailField(blank=True, null=True)
    email_verified = models.BooleanField(default=False)
    city = models.ForeignKey(City, on_delete=models.CASCADE)

client/templates/find_certificate.html
{% extends "template.html" %}
{% load bootstrap %}

{% block title %}לב אחד - התנדב{% endblock %}


{% block body %}
    {% if certificate is not None %}
        {% include "components/get_certificate.html" %}
    {% else %}
        <a style="color: red">{{ error }}</a>
        <form action="{% url 'client_find_certificate' %}" method="post">
            <p>
                רק מתנדבים רשומים במערכת רשאים להנפיק תעודה.
                <br />
                עוד לא נרשמתם כמתנדבים?
                <a href="{% url 'client_volunteer' %}">לחצו כאן</a>
            </p>
            {% csrf_token %}
            {{ form|bootstrap }}
            <input type="submit" class="btn btn-danger" value="חפש תעודה">
        </form>
    {% endif %}
{% endblock %}

client/templates/send_help.html
{% extends "template.html" %}
{% load bootstrap %}

{% block title %}לב אחד - התנדב{% endblock %}


{% block body %}
<form action="send_help" method="post">
    {% csrf_token %}
    {{ form|bootstrap }}
    <input type="submit" value="Submit">
</form>
{% endblock %}

client/templates/template.html
{% load static %}

<!DOCTYPE html>
<html lang="he">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:image" content="{% static 'client/logo.png' %}"/>
    <script
            src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    <script
            src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
            integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
            crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"/>
    <link
            rel="stylesheet"
            href="https://cdn.rtlcss.com/bootstrap/v4.2.1/css/bootstrap.min.css"
            integrity="sha384-vus3nQHTD+5mpDiZ4rkEPlnkcyTP+49BhJ4wJeJunw06ZAp+wzzeBPUXr42fi8If"
            crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'client/main.css' %}">

    <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'client/icon.png' %}"/>

    <!-- Facebook Pixel Code -->
    <script>
        !function (f, b, e, v, n, t, s) {
            if (f.fbq) return;
            n = f.fbq = function () {
                n.callMethod ?
                    n.callMethod.apply(n, arguments) : n.queue.push(arguments)
            };
            if (!f._fbq) f._fbq = n;
            n.push = n;
            n.loaded = !0;
            n.version = '2.0';
            n.queue = [];
            t = b.createElement(e);
            t.async = !0;
            t.src = v;
            s = b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t, s)
        }(window, document, 'script',
            'https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '929295820770466');
        fbq('track', 'PageView');
    </script>
    <noscript>
        <img height="1" width="1" src="https://www.facebook.com/tr?id=929295820770466&ev=PageView&noscript=1"/>
    </noscript>
    <!-- End Facebook Pixel Code -->
    <script>
        $(document).ready(function () {
            $("#id_date_of_birth").datepicker({
                changeYear: true,
                dateFormat: 'dd/mm/yy',
                yearRange: '-100:+0'
            });
        });
    </script>
    {% block extra_scripts %}
    {% endblock %}
</head>
<body dir="rtl">
<div class="page-wrapper">
    <div class="back">
        <nav class="navbar navbar-expand-lg navbar-light">

            <a class="navbar-brand" href="{% url 'client_home' %}">
                <img class="logo" src="{% static 'client/logo.png' %}" alt="My image">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto right">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'client_home' %}">דף הבית</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'client_get_help' %}">בקשת עזרה</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'client_volunteer' %}">התנדבות</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'client_find_certificate' %}">תג ההתנדבות שלי</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"
                           href="https://www.levechad.org/donates">לתרומות</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"
                           href="https://www.levechad.org/about-us">אודותנו</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    <div class="container">
        {% include "translate.html" %}
        {% block body %}
        {% endblock %}
    </div>
    </div>
</div>
<footer class="page-footer" style="width: 100%; background-color: rgba(0, 0, 0, 0.1);
    font-size: 12px; justify-content:center; align-items:center;border-top: 4px solid white;">
    <label class="center"><i> אתר זה נבנה בתרומה ע"י תוכנית תלפיות </i></label>
</footer>


</body>

</html>

client/templates/thanks.html
{% extends "template.html" %}

{% block title %}לב אחד - דף הבית{% endblock %}


{% block body %}
<h1>תודה רבה!</h1>
<h2>אנחנו מעבדים את הבקשה</h2>

<br><br>

{{ message }}

<h4>{{ status }}</h4>
<br>
<h4>מספר פנייה שלך {{ id }}</h4>

{% endblock %}

client/templates/thanks_volunteer.html
{% extends "template.html" %}

{% block title %}לב אחד - דף הבית{% endblock %}
{% block extra_scripts %}
    <!-- send lead notification to facebook !-->
    <script>
        fbq('track', 'Lead');
    </script>
{% endblock %}

{% block body %}
    <h1>תודה רבה מתנדב יקר!</h1>
    <h2>אנחנו מעבדים את הבקשה</h2>

    <br /><br />
    {% include "components/get_certificate.html" %}
{% endblock %}